default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dojo11272
  password: <%= Rails.application.credentials.dig( :database, :password) %>
  host: localhost

development:
  <<: *default
  database: dashool_development

test:
  <<: *default
  database: dashool_test

production:
  <<: *default
  database: dashool_production
