default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dojo11272
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost

development:
  <<: *default
  database: dashool_development

test:
  <<: *default
  database: dashool_test

production:
  <<: *default
  database: <%= ENV["POSTGRES_DATABASE"] %>
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  port: <%= ENV["POSTGRES_PORT"]%>
  host: <%= ENV["POSTGRES_HOST"]%>
